### ISSUE TITLE
Resource Nodes Don't Always Spawn

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#101]
Idk if there is supposed to be a randomization system, or if spawning is just bugged. Either way it's bad.
![image](https://user-images.githubusercontent.com/39461072/131015670-d476f74d-4111-4cc5-a72f-919290988bb5.png)

**Comment by ZenBre4ker** [comment]
Apparently they are there, but don't get synced to the client. This is svphys debug view.
![grafik](https://user-images.githubusercontent.com/72046466/131308539-63e0ef88-941e-4367-ab15-83dc8471e3cb.png)

**Comment by kurozael** [comment]
Believed to be resolved, re-open if I'm wrong 😃

**Comment by gvarados1** [comment]
Not resolved. I don't have permission to re-open.
