### ISSUE TITLE
Enhancement: Show Max Distance on Tunnels

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#110]
Having some sort of white filled opaque circle around a selected tunnel with max distance as radius would help to setup tunnels.

While I rather like tunnels of CnC: Generals, where you put all your units in one tunnel and manually get them out of any other build tunnel I can see where your approach is more fair, but maybe you wanna reconsider 😄

**Comment by kurozael** [comment]
✅
