### ISSUE TITLE
Enhancement: Cheats

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#117]
To make testing faster and easier it would be nice to have some cheats as host like:
-No build time
~~-No costs~~

**Comment by kurozael** [comment]
Just so you know @ZenBre4ker, the command `rts_richboy` will give you 99999 of every resource. However a build time "cheat" would be good as well.

**Comment by kurozael** [comment]
Added `rts_doitnow` which will skip waiting times for building (insta-build) and set the duration of any queueables to 1 second for you.

✅
