### ISSUE TITLE
Missing references to greenlands map

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#118]
Could you upload the missing references in the tileset folder?
![grafik](https://user-images.githubusercontent.com/72046466/131331755-00efcdd3-5d2e-4056-b011-6084651d8d7e.png)

**Comment by ZenBre4ker** [comment]
And for the eclipse map
![grafik](https://user-images.githubusercontent.com/72046466/131331840-bd8bc94e-5aa0-4125-a517-648b29d96836.png)

**Comment by ZenBre4ker** [comment]
Probably something to do by @bakscratch, right?

**Comment by bakscratch** [comment]
Should be up now 👍

**Comment by ZenBre4ker** [comment]
Looks good for greenlands, only the firefly.vpcf are missing now.

Still the same with the eclipse map.
