### ISSUE TITLE
Enhancement: Delete csproj-files for easier PRs

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#119]
As I have another file path for sbox, I always need to change the path in code/sbox-rts.csproj when I start a PR.
I am not familiar enough with Github, but as we added it to the gitignore with last commit, it should be enough to delete it on the repo.
![grafik](https://user-images.githubusercontent.com/72046466/131486378-ba145679-441a-4777-a8c9-bdc66d6c912f.png)

**Comment by ZenBre4ker** [comment]
In Sandbox they just have all *csproj added and deleted them on github
https://github.com/Facepunch/sandbox/blob/master/.gitignore

**Comment by kurozael** [comment]
✅
