### ISSUE TITLE
Server Crashed - MESSAGE_PARSE_ERROR

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#127]
The server crashed when we were playing a game. Here's the disconnect message & console.
![image](https://user-images.githubusercontent.com/39461072/132930274-25fef222-419a-4a97-9ade-d3b89a11d1d7.png)
![image](https://user-images.githubusercontent.com/39461072/132930278-84c55a9d-6f8f-426e-8d95-6fe2caa3b4d1.png)

**Comment by kurozael** [comment]
Known s&box issue - not RTS specific.
