### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#134]
A lot of the icons are missing for Resources/Buildings/Units/Abilities
![image](https://user-images.githubusercontent.com/39461072/152232853-e2d98e09-cef4-4d02-8b79-8dbb79800d6e.png)

**Comment by handsomematt** [comment]
Need to pass filesystem to Texture.Load

**Comment by kurozael** [comment]
I did fix all of these (what @handsomematt said) but must not have pushed it. Cheers.
