### ISSUE TITLE
Units Get Stuck On Terrain

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#135]
Units get stuck on the terrain sometimes. Here's a spot that always traps units, but there are a lot more.
If a unit gets stuck, it can't move at all. You have to kill the unit.

![image](https://user-images.githubusercontent.com/39461072/152233154-f68ed4cb-8075-4359-91d5-0d8d3dd8a271.png)

**Comment by kurozael** [comment]
Thanks for providing a repro. I'll investigate.
