### ISSUE TITLE
Tiny Lights Prevent Building

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#137]
I can't build on these tiny lights. They're so hard to see and the building placement actually shows green but won't let me place there.
Maybe just disable collisions on them?

![image](https://user-images.githubusercontent.com/39461072/152233887-7a960c0c-fc43-4db8-8358-0e47fe6cd83e.png)

**Comment by kurozael** [comment]
One for Louie. Cheers!

**Comment by gvarados1** [comment]
The other map has this same issue
