### ISSUE TITLE
Infantry Unit Becomes Invisible When It's Vehicle Is Destroyed

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#144]
Infantry units become invisible when the vehicle gets destroyed. They still function as normal but aren't rendering.
Really, the should be killed when the vehicle is destroyed. Manually ejecting your unit right before the vehicle explodes is a skill thing.

![image](https://user-images.githubusercontent.com/39461072/152268335-d0400bf3-880b-4cd0-9bf9-f0750a37d56b.png)

**Comment by kurozael** [comment]
I'll sort both of these concerns out 👌

**Comment by kurozael** [comment]
This should be sorted. Occupants of a vehicle actually take a percentage of damage anyway, so you can still evict them to mitigate this.
