### ISSUE TITLE
Visuals for when units are inside buildings/vehicles

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#145]
We need to be able to see when a unit is inside a vehicle/Pub/Watchtower/Pillbox. Just add windows to the buildings and nodes for the units to be placed on

**Comment by kurozael** [comment]
Is there a reason why the UI indicator isn't good enough? Or is this just purely for aesthetics?

**Comment by gvarados1** [comment]
You need to know what you're going up against. If you spot an enemy pillbox early, you need to be able to instantly know if it has enemies in it and what types.

Same for vehicles. Vehicles are basically a mystery enemy. You have no clue what the enemy is until it attacks you or you manually click on it (if you even can click to see what's inside an enemy vehicle?)

**Comment by kurozael** [comment]
I think I'll start by adding clicking on an enemy unit to view its passengers / inhabitants. Showing the units themselves inside will come down the line with the proper art pass 👌

**Comment by gvarados1** [comment]
Might be good to just tint the vehicle color as a temporary solution. In the half second it takes to click an enemy and find out, they could have either ran away if weaker, or killed half your squad if much stronger.
