### ISSUE TITLE
Better AI when infantry is inside a vehicle

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#146]
We can't control what the infantry inside the vehicle is doing. I had a Buggy with an infantry inside it, but it was completely useless because it kept shooting the enemy's buildings instead of the enemy units. I targeted a unit and the infantry continued firing at the building.

I think it might be better if these vehicles didn't have passengers, and instead just had weapons built-in. It's a cool mechanic that might work if all the systems are there, but I don't see it currently.

I think we'd need a proper infantry+vehicle control system, like what CoH2 has for this to be good.

**Comment by kurozael** [comment]
I'd really like to keep this mechanic in and it's a bit different. I think just making sure they attack what you've told them to as a priority would be good enough for now.
