### ISSUE TITLE
turret kills one unit, stops killing others 

### ISSUE THREAD

**Issue by svensis** [Facepunch/sbox-rts#56]
doesnt shoot the ones after
![lZxiyd4](https://user-images.githubusercontent.com/11571941/129339632-bfe187ea-4713-4b7c-9505-e33d6216fba2.png)

**Comment by kurozael** [comment]
Unable to reproduce... aren't they your units?

**Comment by tavichh** [comment]
I can attest to this. Do you think this is because I clicked the turret to interrupt the attack order?

**Comment by kurozael** [comment]
@tavichh You can't actually tell a Turret what to attack so that's weird.

**Comment by svensis** [comment]
https://cdn.discordapp.com/attachments/234973064885043200/875710456285777920/bbb.mp4
