### ISSUE TITLE
unit walked into a hill and got stuck 

### ISSUE THREAD

**Issue by svensis** [Facepunch/sbox-rts#58]
![7YZZG3j](https://user-images.githubusercontent.com/11571941/129341677-802b6c5a-462e-4a80-92e8-60d4f4c59ad1.jpeg)
he cant move anymore

**Comment by svensis** [comment]
set him on autowalk to walk on the other side of the map, and now he is in a place where he cant move out of it

**Comment by kurozael** [comment]
Potentially fixed. Let me know if you're able to reproduce it :)
