### ISSUE TITLE
The addition of a market building would be lovely.

### ISSUE THREAD

**Issue by tavichh** [Facepunch/sbox-rts#59]
If you have a building such as a brewery which grants you passive resource generation; you should be able to sell said resource to buy other resources. Either a singular building located in the center of the map or a building that mimicks markets in other RTS games.

**Comment by kurozael** [comment]
@bakscratch Could we get a placeholder Market building?

**Comment by bakscratch** [comment]
<img width="662" alt="sbox_zbSMzHNZcg" src="https://user-images.githubusercontent.com/8184184/129364653-9ddd65df-3de0-43bf-bf32-b01477189497.png">
 @kurozael Yup!
