### ISSUE TITLE
Dome Shield Particle Effect Enhancements

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-rts#6]
- Shield fades out too quickly (can we make it fade out when the particle system is destroyed?)
- Can we make CP#2 control the shield color (R, G, B) so that it can interpolate from green to red as it loses health?
- Shield is too bright, especially during day time, it is difficult to see units inside of it
- Shield should follow CP#0 so that it moves with the unit that owns it

**Comment by bakscratch** [comment]
https://files.facepunch.com/louie/1b2711b1/particles_weapons_bubble_guard_bubble_guard.vpcf%20_%202021-07-27%2020-47-04.mp4

Some progress, will probably drop the floating bits.
Need to work out the color stuff, but might be hard due to shader.

**Comment by kurozael** [comment]
Nice one @bakscratch, it doesn't seem to scale with radius on CP#1 or follow CP#0 (I don't know how difficult that'll be, but units can move with their shield). Also, I don't know if you've tried it in-game but it's lit weird, it looks kinda gray and you can't see through it very well.

**Comment by bakscratch** [comment]
Seem to have a bug where it spawns 2? Not sure if this is down to me doing something or your end?

https://files.facepunch.com/louie/1b2811b1/s%26box%202021-07-28%2000-20-42.mp4

**Comment by bakscratch** [comment]
Got scaling set up with cp1 you have to do xyz with the same value to scale the bubble correctly.
CP2 controls the health color, also added a little more visual effects.

https://files.facepunch.com/louie/1b2811b1/particles_weapons_bubble_guard_bubble_guard.vpcf%202021-07-28%2014-11-46.mp4
