### ISSUE TITLE
Movement Confirmation Marker / Effect

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-rts#64]

**Comment by kurozael** [comment]
When you tell a unit or group of units to move somewhere there should be a particle effect play where you click to indicate they are moving there, that sort of thing.

**Comment by bakscratch** [comment]
https://files.facepunch.com/louie/1b1711b1/particles_movement_marker_movement_marker.vpcf%202021-08-17%2017-55-13.mp4

Something like this? You can change the colour, maybe it changes on if attacking or moving?

**Comment by bakscratch** [comment]
The particles not showing correctly has also been fixed.
