### ISSUE TITLE
SAM Site Placeholder

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-rts#7]
- Should be able to rotate 360 degrees similar to the Turret
- Should be able to pitch up about 45 degrees to fire at aircraft
- Should have 6 muzzle attachments (muzzle1, muzzle2, etc)

**Comment by bakscratch** [comment]
I have pushed a version with this, I haven't tested if the aiming works correctly but should be the same as the turret with angle up.

**Comment by kurozael** [comment]
When angling up, it seems to "twist" a little. I'm not sure if this is an animgraph issue or an issue with the bone transforms.

**Comment by bakscratch** [comment]
> When angling up, it seems to "twist" a little. I'm not sure if this is an animgraph issue or an issue with the bone transforms.

I'll look into this today, see if I can clean it up. Maybe @MaxLebled might also know?

**Comment by MaxLebled** [comment]
Can you show me what's happening exactly?

**Comment by bakscratch** [comment]
I think I may have just fixed it. 
https://files.facepunch.com/louie/1b0311b1/s%26box%202021-08-03%2010-52-13.mp4

It was doing this before,
https://files.facepunch.com/louie/1b0311b1/s%26box%202021-08-03%2010-54-04.mp4
