### ISSUE TITLE
Outline units when they're behind a building

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#71]
Outline units when they're behind a building

Workers commonly spawn behind the command centre, and I don't know that they're there until I box select the area
![image](https://user-images.githubusercontent.com/39461072/130269148-e2bb48f3-1a0b-4983-9873-31edfedf50ea.png)

**Comment by kurozael** [comment]
For now I've made them visible through buildings but in the future this will only be an outline.
