### ISSUE TITLE
Sort selected units by type, press tab to switch between them

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#73]
Selected units should be sorted by type. and we should be able to switch between the main selected unit by pressing tab.

This way, I can switch between unit's abilities without having to select that individual unit, then re-selecting my group when finished.

![image](https://user-images.githubusercontent.com/39461072/130269853-d6beb2be-7852-4abf-9e24-2d81756ef2de.png)

**Comment by kurozael** [comment]
✅
