### ISSUE TITLE
Make fog of war not completely black

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#75]
This isn't a pve mode. We should be able to see the entire map even when we haven't traveled there.

Having a completely black fog of war is a terrible idea for pvp. Players that have the map memorized (or have a screenshot of the complete map open) have an INSANE advantage, making it basically impossible for people who don't know the map to even stand a chance.

**Comment by kurozael** [comment]
I did this because Age of Empires has it completely black - but I'll look into this.

**Comment by kurozael** [comment]
✅
