### ISSUE TITLE
Ability to add buildings to groups

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#76]
Buildings should be able to be added to groups. This also goes along with #73 Most RTS players have all their buildings on one group, and press tab to switch between them, allowing them to build units quickly.

![image](https://user-images.githubusercontent.com/39461072/130271035-15c94fce-d9e5-44ed-851e-ed8dd811c049.png)

**Comment by kurozael** [comment]
So there's two things here:

1. Let buildings be added to groups. This would also mean you can select a building and a unit at the same time?
2. Tab should switch between units in the current selection?

**Comment by gvarados1** [comment]
1. Don't know if units & buildings should vr selectable at the same time.
Probably not.

2. Yes

**Comment by kurozael** [comment]
✅
