### ISSUE TITLE
Add hotkeys to building / unit abilities

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#77]
Units/Buildings should have hotkeys for their abilities

![image](https://user-images.githubusercontent.com/39461072/130271409-e939a7cf-d6a8-4f8c-99bc-4b57ae808628.png)
![image](https://user-images.githubusercontent.com/39461072/130271625-b261d46e-41de-449c-9198-1440a28bb818.png)

**Comment by kurozael** [comment]
Hotkeys are coming once there's better support for them in s&box itself.
