### ISSUE TITLE
Sort Buildables Into Seperate Categories 

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#78]
The workers should have categories for the buildings, instead of having a huge confusing list

![image](https://user-images.githubusercontent.com/39461072/130272306-00cabbe3-0a3f-43ed-91c1-422b28cdf664.png)

**Comment by kurozael** [comment]
I was trying to avoid extra clicks where possible - but I'll look into this.

**Comment by kurozael** [comment]
I don't think I'll put into categories and keep them like AoE but will figure something out for sorting the items.
