### ISSUE TITLE
Double tap to focus camera on group.

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#79]
We should be able to double tap a group hotkey to focus the camera on it
![image](https://user-images.githubusercontent.com/39461072/130272631-872ae9e2-7fef-4767-9509-548edf2aa165.png)

**Comment by kurozael** [comment]
What should happen if the group has units that are far away from each other? Should it just centre the camera in middle of the bounds of the whole group even if one unit is in one corner of the map and one is in another? (Genuine question.)

**Comment by kurozael** [comment]
Also do you mean tap not tab? For example pressing 2 twice in quick succession?

**Comment by gvarados1** [comment]
Double tap sorry

**Comment by gvarados1** [comment]
Don't know. Maybe it should focus on the first unit in the group?

**Comment by kurozael** [comment]
✅
