### ISSUE TITLE
Launch Pad Placeholder

### ISSUE THREAD

**Issue by kurozael** [Facepunch/sbox-rts#8]
- Placeholder structure which the Nuke ability will be used from
- Should be about the same size as the Pub

**Comment by bakscratch** [comment]
Something like this?
https://files.facepunch.com/louie/1b2811b1/f__sbox_sbox-game_addons_sbox-rts_models_buildings_nuke_launch_site_nuke_launch_site.vanmgrph%202021-07-28%2019-29-33.mp4

Has animation to open the hatch.

**Comment by kurozael** [comment]
Damn, very nice! Especially with the added animation <3
