### ISSUE TITLE
Remove range limit on nuke/airstrike

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#82]
The nuke & air striek seem to have a very tiny range limit, making them basically useless. It's probably best to be able to use these on any area that the player currently has units in / is being scanned.

**Comment by kurozael** [comment]
You're supposed to build launch pads / command centres within range of your target - but I haven't verified how short the range is exactly on the larger test maps.

**Comment by kurozael** [comment]
Distance increased by 3x for now but I like the idea of only using it on seen areas so I'll move this to a dedicated ticket.
