### ISSUE TITLE
Ability to Select Enemy Units

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#89]
We should be able to select enemy units to view it's description.
![image](https://user-images.githubusercontent.com/39461072/130342084-75660b79-ea66-4530-bfb7-6679ff84e2b2.png)

**Comment by kurozael** [comment]
Would you be happy for this to be a tooltip instead, like when you hover over resources?

**Comment by gvarados1** [comment]
I think we should be able to see the entire description, including it's
resistances and dps.

**Comment by kurozael** [comment]
✅
