### ISSUE TITLE
Remove Worker Construction Range

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#90]
Workers shouldn't have a limited range on where they can build.
I should be able to just have my worked build a silo, instead of having it walk there first, then clicking it again and building.

**Comment by kurozael** [comment]
If I've seen enemy territory wouldn't I just be able to place a bunch of silos all over their territory from across the map to annoy them?

**Comment by gvarados1** [comment]
It shouldn't even depend on if you've seen the territory. We should be able
to just build anywhere.
Workers would still have to walk to the location to build it, so this
doesn't affect annoying building spam. Plus if you get enemy silos in your
base it's your fault for not killing the worker lol

**Comment by kurozael** [comment]
Right but they’ll see a silo pop up out of nowhere ready to be built because you placed down the construction site from the other side of the map…

**Comment by gvarados1** [comment]
Don't show construction plan to enemy until worker has started constructing, do a second check to make sure the spot is still valid after walking to it.

**Comment by kurozael** [comment]
I’m trying to remember how AoE did it, I think I’m gonna have to think a bit about this. Because now it might get a bit confusing.

**Comment by gvarados1** [comment]
AoE probably had the system that's currently ingame, because it has a completely black fog of war.
