### ISSUE TITLE
Show Unit Movement Path

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-rts#92]
When I select a unit, I should see a line showing me where the unit is walking to, including any queued movements.

**Comment by kurozael** [comment]
> When I select a unit, I should see a line showing me where the unit is walking to, including any queued movements.

Probably not gonna be possible because the game uses flowfield pathfinding. What I could do is render a direct line to its goal but I wouldn't be able to show the path it will take.

**Comment by gvarados1** [comment]
Direct line would be better than nothing, but still not ideal.
I assume you're still working on nav? Units sometimes get confused and
don't construct buildings or harvest resources until I move them to a
different location and give them the order again.

**Comment by kurozael** [comment]
Sometimes the interaction range is a little off. But as for nav I chose flowfields because they are stupidly fast for many units at once, it’s commonly used in RTS. What is good about seeing paths over just seeing markers to indicate their goal?

**Comment by gvarados1** [comment]
That could work

**Comment by ZenBre4ker** [comment]
As a RTS fan, just saying that a straight line makes it way easier to see where the units where supposed to go on the fly, where as with just a marker you have to search for it. Especially when units are automatically moving it's most often not clear where they will go. So a line indicating it, makes it just faster to find the direction and spot 😄

**Comment by bakscratch** [comment]
Pushed a particle for this 👍

**Comment by kurozael** [comment]
Added support for this @bakscratch but can't get them to actually display?
