### ISSUE TITLE
Feature Request: Allow public games

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#93]
Right now it's only possible to join friends, there are no lobbies visiblee one could join.
Is that intended behavior?

![grafik](https://user-images.githubusercontent.com/72046466/130606016-944dd13f-8cf5-4878-bad6-c39b9f0e2470.png)

**Comment by ZenBre4ker** [comment]
I guess you need to add the tag Multiplayer to your game. Would make it easier for us to test games with random players instead of with friends ❤️ 
![grafik](https://user-images.githubusercontent.com/72046466/130660299-85d84868-193a-4915-b0f4-770d955033c2.png)

**Comment by kurozael** [comment]
Sorted, thanks for reporting! ✅
