### ISSUE TITLE
Bug: Camera Movement Lags

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#94]
If you move over the map with WASD the map lags, it feels like a scroll animation is restarted and you get beamed to the last point while still moving in the right direction. The screen seemingly lags/tears apart.

**Comment by ZenBre4ker** [comment]
Looking at the code this probably comes from prediction. With time.delta being different on server and client, this means, that the camera position gets reset.
https://github.com/Facepunch/sbox-rts/blob/master/code/entities/Player.cs#L290-L311

I see there is a camera class already made, so I guess you already plan to move code there and make it clientside only. I don't see any use to have that info on the server anyway.

**Comment by kurozael** [comment]
I'm not experiencing this. There are a lot of valid reasons for the server to know where the client is looking, that's why the camera is predicted.
