### ISSUE TITLE
Feature Request: Minimap

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/sbox-rts#96]
It's hard to move across the map and see where you might get attacked. A Minimap or radar would be cool. I read that there is a radar shield, but in our session I didnt find something like a radar, probably to reveal enemy units.

**Comment by ZenBre4ker** [comment]
Seeing #67 I am sorry for posting this, but how do you get a minimap or is it not finished yet?

**Comment by kurozael** [comment]
It isn't finished yet :)
